//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 06:38:56 PM CET 
//


package com.ftn.xml.model.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}podaci_o_organu"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}podaci_o_podnosiocu"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOOrganu",
    "podaciOPodnosiocu"
})
@XmlRootElement(name = "osnovni_podaci")
public class OsnovniPodaci {

    @XmlElement(name = "podaci_o_organu", required = true)
    protected PodaciOOrganu podaciOOrganu;
    @XmlElement(name = "podaci_o_podnosiocu", required = true)
    protected PodaciOPodnosiocu podaciOPodnosiocu;

    /**
     * Gets the value of the podaciOOrganu property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOOrganu }
     *     
     */
    public PodaciOOrganu getPodaciOOrganu() {
        return podaciOOrganu;
    }

    /**
     * Sets the value of the podaciOOrganu property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOOrganu }
     *     
     */
    public void setPodaciOOrganu(PodaciOOrganu value) {
        this.podaciOOrganu = value;
    }

    /**
     * Gets the value of the podaciOPodnosiocu property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOPodnosiocu }
     *     
     */
    public PodaciOPodnosiocu getPodaciOPodnosiocu() {
        return podaciOPodnosiocu;
    }

    /**
     * Sets the value of the podaciOPodnosiocu property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOPodnosiocu }
     *     
     */
    public void setPodaciOPodnosiocu(PodaciOPodnosiocu value) {
        this.podaciOPodnosiocu = value;
    }

}
