//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 06:38:56 PM CET 
//


package com.ftn.xml.model.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}naziv"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}sediste"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}broj_predmeta"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}datum_zahteva"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naziv",
    "sediste",
    "brojPredmeta",
    "datumZahteva"
})
@XmlRootElement(name = "podaci_o_organu")
public class PodaciOOrganu {

    @XmlElement(required = true)
    protected Naziv naziv;
    @XmlElement(required = true)
    protected Sediste sediste;
    @XmlElement(name = "broj_predmeta", required = true)
    protected BrojPredmeta brojPredmeta;
    @XmlElement(name = "datum_zahteva", required = true)
    protected DatumZahteva datumZahteva;

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link Naziv }
     *     
     */
    public Naziv getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Naziv }
     *     
     */
    public void setNaziv(Naziv value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the sediste property.
     * 
     * @return
     *     possible object is
     *     {@link Sediste }
     *     
     */
    public Sediste getSediste() {
        return sediste;
    }

    /**
     * Sets the value of the sediste property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sediste }
     *     
     */
    public void setSediste(Sediste value) {
        this.sediste = value;
    }

    /**
     * Gets the value of the brojPredmeta property.
     * 
     * @return
     *     possible object is
     *     {@link BrojPredmeta }
     *     
     */
    public BrojPredmeta getBrojPredmeta() {
        return brojPredmeta;
    }

    /**
     * Sets the value of the brojPredmeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrojPredmeta }
     *     
     */
    public void setBrojPredmeta(BrojPredmeta value) {
        this.brojPredmeta = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link DatumZahteva }
     *     
     */
    public DatumZahteva getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatumZahteva }
     *     
     */
    public void setDatumZahteva(DatumZahteva value) {
        this.datumZahteva = value;
    }

}
