//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:02:09 PM CET 
//


package com.ftn.xml.model.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/ns/obavestenje}potpis_ovlascenog_lica"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "potpisOvlascenogLica"
})
@XmlRootElement(name = "podnozje")
public class Podnozje {

    @XmlElement(name = "potpis_ovlascenog_lica", required = true)
    protected PotpisOvlascenogLica potpisOvlascenogLica;

    /**
     * Gets the value of the potpisOvlascenogLica property.
     * 
     * @return
     *     possible object is
     *     {@link PotpisOvlascenogLica }
     *     
     */
    public PotpisOvlascenogLica getPotpisOvlascenogLica() {
        return potpisOvlascenogLica;
    }

    /**
     * Sets the value of the potpisOvlascenogLica property.
     * 
     * @param value
     *     allowed object is
     *     {@link PotpisOvlascenogLica }
     *     
     */
    public void setPotpisOvlascenogLica(PotpisOvlascenogLica value) {
        this.potpisOvlascenogLica = value;
    }

}
