//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.04 at 11:51:28 AM CET 
//


package com.ftn.xml.model.izvestaj;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.model.izvestaj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BrojOdbijenihZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/izvestaj", "broj_odbijenih_zahteva");
    private final static QName _BrojZalbiNaCutanje_QNAME = new QName("http://www.ftn.uns.ac.rs/izvestaj", "broj_zalbi_na_cutanje");
    private final static QName _BrojZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/izvestaj", "broj_zahteva");
    private final static QName _BrojZalbiNaOdluku_QNAME = new QName("http://www.ftn.uns.ac.rs/izvestaj", "broj_zalbi_na_odluku");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.model.izvestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaIzvestaja }
     * 
     */
    public ListaIzvestaja createListaIzvestaja() {
        return new ListaIzvestaja();
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/izvestaj", name = "broj_odbijenih_zahteva")
    public JAXBElement<BigInteger> createBrojOdbijenihZahteva(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojOdbijenihZahteva_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/izvestaj", name = "broj_zalbi_na_cutanje")
    public JAXBElement<BigInteger> createBrojZalbiNaCutanje(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojZalbiNaCutanje_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/izvestaj", name = "broj_zahteva")
    public JAXBElement<BigInteger> createBrojZahteva(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojZahteva_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/izvestaj", name = "broj_zalbi_na_odluku")
    public JAXBElement<BigInteger> createBrojZalbiNaOdluku(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojZalbiNaOdluku_QNAME, BigInteger.class, null, value);
    }

}
