package com.ftn.xml.soap.zahtev_za_izjasnjenje_odluka;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T19:38:45.187+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ZahtevZaIzjasnjenjeOdlukaService", 
                  wsdlLocation = "classpath:wsdl/zahtev_za_izjasnjenje_odluka.wsdl",
                  targetNamespace = "http://ftn.uns.ac.rs/zalba_na_odluku") 
public class ZahtevZaIzjasnjenjeOdlukaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ftn.uns.ac.rs/zalba_na_odluku", "ZahtevZaIzjasnjenjeOdlukaService");
    public final static QName ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding = new QName("http://ftn.uns.ac.rs/zalba_na_odluku", "ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding");
    static {
        URL url = ZahtevZaIzjasnjenjeOdlukaService.class.getClassLoader().getResource("wsdl/zahtev_za_izjasnjenje_odluka.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZahtevZaIzjasnjenjeOdlukaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/zahtev_za_izjasnjenje_odluka.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public ZahtevZaIzjasnjenjeOdlukaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZahtevZaIzjasnjenjeOdlukaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZahtevZaIzjasnjenjeOdlukaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZahtevZaIzjasnjenjeOdlukaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZahtevZaIzjasnjenjeOdlukaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZahtevZaIzjasnjenjeOdlukaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZahtevZaIzjasnjenjeOdlukaServicePortType
     */
    @WebEndpoint(name = "ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding")
    public ZahtevZaIzjasnjenjeOdlukaServicePortType getZahtevZaIzjasnjenjeOdlukaServiceSoapBinding() {
        return super.getPort(ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding, ZahtevZaIzjasnjenjeOdlukaServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZahtevZaIzjasnjenjeOdlukaServicePortType
     */
    @WebEndpoint(name = "ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding")
    public ZahtevZaIzjasnjenjeOdlukaServicePortType getZahtevZaIzjasnjenjeOdlukaServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding, ZahtevZaIzjasnjenjeOdlukaServicePortType.class, features);
    }

}
