package com.ftn.xml.soap.zahtev_za_izjasnjenje_odluka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ftn.xml.model.zalba_na_odluku.ObjectFactory;
import com.ftn.xml.model.zalba_na_odluku.ZalbaNaOdluku;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T19:38:45.179+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://ftn.uns.ac.rs/zalba_na_odluku", name = "ZahtevZaIzjasnjenjeOdlukaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZahtevZaIzjasnjenjeOdlukaServicePortType {

    @WebMethod(action = "http://www.ftn.uns.ac.rs/zahtev_za_izjasnjenje_odluka/ws/dodajZahtevZaIzjasnjenjeOdluka")
    @WebResult(name = "ok", targetNamespace = "http://ftn.uns.ac.rs/zalba_na_odluku", partName = "ok")
    public java.lang.String dodajZahtevZaIzjasnjenjeOdluka(
        @WebParam(partName = "zalba_na_odluku", name = "zalba_na_odluku")
        ZalbaNaOdluku zalbaNaOdluku
    );

    @WebMethod(action = "http://www.ftn.uns.ac.rs/zahtev_za_izjasnjenje_odluka/ws/izbrisiZahtevZaIzjasnjenjeOdluka")
    @WebResult(name = "ok", targetNamespace = "http://ftn.uns.ac.rs/zalba_na_odluku", partName = "ok")
    public java.lang.String izbrisiZahtevZaIzjasnjenjeOdluka(
        @WebParam(partName = "id_zalbe", name = "id_zalbe")
        java.lang.String idZalbe
    );
}
