
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ftn.xml.soap.zahtev_za_izjasnjenje_odluka;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ftn.xml.model.zalba_na_odluku.ZalbaNaOdluku;
import com.ftn.xml.service.ZahtevZaIzjasnjenjeOdlukaService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T19:38:45.134+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZahtevZaIzjasnjenjeOdlukaService",
                      portName = "ZahtevZaIzjasnjenjeOdlukaServiceSoapBinding",
                      targetNamespace = "http://ftn.uns.ac.rs/zalba_na_odluku",
                      wsdlLocation = "src/main/resources/static/wsdl/zahtev_za_izjasnjenje_odluka.wsdl",
                      endpointInterface = "com.ftn.xml.soap.zahtev_za_izjasnjenje_odluka.ZahtevZaIzjasnjenjeOdlukaServicePortType")
@Service            
public class ZahtevZaIzjasnjenjeOdlukaServiceSoapBindingImpl implements ZahtevZaIzjasnjenjeOdlukaServicePortType {

    private static final Logger LOG = Logger.getLogger(ZahtevZaIzjasnjenjeOdlukaServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.zalba_na_odluku.ZahtevZaIzjasnjenjeOdlukaServicePortType#dodajZahtevZaIzjasnjenjeOdluka(rs.ac.uns.ftn.zalba_na_odluku.ZalbaNaOdluku zalbaNaOdluku)*
     */
    
    @Autowired
    private ZahtevZaIzjasnjenjeOdlukaService zahtevService;
    
    public java.lang.String dodajZahtevZaIzjasnjenjeOdluka(ZalbaNaOdluku zalbaNaOdluku) { 
        LOG.info("Executing operation dodajZahtevZaIzjasnjenjeOdluka");
        System.out.println(zalbaNaOdluku);
        try {
        	this.zahtevService.dodajZahtevZaIzjasnjenjeOdluka(zalbaNaOdluku);
            java.lang.String _return = "OK";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.zalba_na_odluku.ZahtevZaIzjasnjenjeOdlukaServicePortType#izbrisiZahtevZaIzjasnjenjeOdluka(java.lang.String idZalbe)*
     */
    public java.lang.String izbrisiZahtevZaIzjasnjenjeOdluka(java.lang.String idZalbe) { 
        LOG.info("Executing operation izbrisiZahtevZaIzjasnjenjeOdluka");
        System.out.println(idZalbe);
        try {
        	this.zahtevService.izbrisiZahtevZaIzjasnjenjeOdluka(idZalbe);
            java.lang.String _return = "OK";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
