//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 07:03:30 PM CET 
//


package com.ftn.jaxb.zalba_cutanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="nije_postupio">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nije_postupio_u_celosti">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nije_postupio_u_roku">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nijePostupio",
    "nijePostupioUCelosti",
    "nijePostupioURoku"
})
@XmlRootElement(name = "razlog_zalbe")
public class RazlogZalbe {

    @XmlElement(name = "nije_postupio")
    protected RazlogZalbe.NijePostupio nijePostupio;
    @XmlElement(name = "nije_postupio_u_celosti")
    protected RazlogZalbe.NijePostupioUCelosti nijePostupioUCelosti;
    @XmlElement(name = "nije_postupio_u_roku")
    protected RazlogZalbe.NijePostupioURoku nijePostupioURoku;

    /**
     * Gets the value of the nijePostupio property.
     * 
     * @return
     *     possible object is
     *     {@link RazlogZalbe.NijePostupio }
     *     
     */
    public RazlogZalbe.NijePostupio getNijePostupio() {
        return nijePostupio;
    }

    /**
     * Sets the value of the nijePostupio property.
     * 
     * @param value
     *     allowed object is
     *     {@link RazlogZalbe.NijePostupio }
     *     
     */
    public void setNijePostupio(RazlogZalbe.NijePostupio value) {
        this.nijePostupio = value;
    }

    /**
     * Gets the value of the nijePostupioUCelosti property.
     * 
     * @return
     *     possible object is
     *     {@link RazlogZalbe.NijePostupioUCelosti }
     *     
     */
    public RazlogZalbe.NijePostupioUCelosti getNijePostupioUCelosti() {
        return nijePostupioUCelosti;
    }

    /**
     * Sets the value of the nijePostupioUCelosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link RazlogZalbe.NijePostupioUCelosti }
     *     
     */
    public void setNijePostupioUCelosti(RazlogZalbe.NijePostupioUCelosti value) {
        this.nijePostupioUCelosti = value;
    }

    /**
     * Gets the value of the nijePostupioURoku property.
     * 
     * @return
     *     possible object is
     *     {@link RazlogZalbe.NijePostupioURoku }
     *     
     */
    public RazlogZalbe.NijePostupioURoku getNijePostupioURoku() {
        return nijePostupioURoku;
    }

    /**
     * Sets the value of the nijePostupioURoku property.
     * 
     * @param value
     *     allowed object is
     *     {@link RazlogZalbe.NijePostupioURoku }
     *     
     */
    public void setNijePostupioURoku(RazlogZalbe.NijePostupioURoku value) {
        this.nijePostupioURoku = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NijePostupio {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NijePostupioUCelosti {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NijePostupioURoku {


    }

}
