package com.ftn.xml.soap.odgovor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ftn.xml.model.odgovor_zahtev_za_izjasnjenje.ObjectFactory;
import com.ftn.xml.model.odgovor_zahtev_za_izjasnjenje.OdgovorZahtevZaIzjasnjenje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T17:37:51.993+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://ftn.uns.ac.rs/izjasnjenje/odgovor", name = "OdgovorZahtevZaIzjasnjenjeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OdgovorZahtevZaIzjasnjenjeServicePortType {

    @WebMethod(action = "http://www.ftn.uns.ac.rs/odgovor_zahtev_za_izjasnjenje/ws/izbrisiOdgovorZahtevZaIzjasnjenje")
    @WebResult(name = "ok", targetNamespace = "http://ftn.uns.ac.rs/izjasnjenje/odgovor", partName = "ok")
    public java.lang.String izbrisiOdgovorZahtevZaIzjasnjenje(
        @WebParam(partName = "id_zalbe", name = "id_zalbe")
        java.lang.String idZalbe
    );

    @WebMethod(action = "http://www.ftn.uns.ac.rs/odgovor_zahtev_za_izjasnjenje/ws/dodajOdgovorZahtevZaIzjasnjenje")
    @WebResult(name = "ok", targetNamespace = "http://ftn.uns.ac.rs/izjasnjenje/odgovor", partName = "ok")
    public java.lang.String dodajOdgovorZahtevZaIzjasnjenje(
        @WebParam(partName = "odgovor_zahtev_za_izjasnjenje", name = "odgovor_zahtev_za_izjasnjenje")
        OdgovorZahtevZaIzjasnjenje odgovorZahtevZaIzjasnjenje
    );
}
