package com.ftn.xml.soap.zahtev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ftn.xml.model.zahtev.ListaZahtevaZaPristupInformacijama;
import com.ftn.xml.model.zahtev.ObjectFactory;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-31T14:16:23.865+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/zahtev", name = "ZahtevServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZahtevServicePortType {

    @WebMethod(action = "http://www.ftn.uns.ac.rs/zahtev/ws/pronadjiOdbijeneZahteve")
    @WebResult(name = "zahtevi", targetNamespace = "http://www.ftn.uns.ac.rs/zahtev", partName = "zahtevi")
    public ListaZahtevaZaPristupInformacijama pronadjiOdbijeneZahteve(
        @WebParam(partName = "email", name = "email")
        java.lang.String email
    );
    
    @WebMethod(action = "http://www.ftn.uns.ac.rs/zahtev/ws/pronadjiNeodgovoreneZahteve")
    @WebResult(name = "zahtevi", targetNamespace = "http://www.ftn.uns.ac.rs/zahtev", partName = "zahtevi")
    public ListaZahtevaZaPristupInformacijama pronadjiNeodgovoreneZahteve(
        @WebParam(partName = "email", name = "email")
        java.lang.String email
    );
}
