//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:05:34 PM CET 
//

package com.ftn.xml.model.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}tekst_obrazlozenja"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}sud"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}taksa"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "tekstObrazlozenja", "sud", "taksa" })
@XmlRootElement(name = "obrazlozenje")
public class Obrazlozenje {

	@XmlElement(name = "tekst_obrazlozenja", required = true)
	protected String tekstObrazlozenja;
	@XmlElement(required = true)
	protected String sud;
	@XmlElement(required = true)
	protected Taksa taksa;

	/**
	 * Gets the value of the tekstObrazlozenja property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTekstObrazlozenja() {
		return tekstObrazlozenja;
	}

	/**
	 * Sets the value of the tekstObrazlozenja property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTekstObrazlozenja(String value) {
		this.tekstObrazlozenja = value;
	}

	/**
	 * Gets the value of the sud property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSud() {
		return sud;
	}

	/**
	 * Sets the value of the sud property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setSud(String value) {
		this.sud = value;
	}

	/**
	 * Gets the value of the taksa property.
	 * 
	 * @return possible object is {@link Taksa }
	 * 
	 */
	public Taksa getTaksa() {
		return taksa;
	}

	/**
	 * Sets the value of the taksa property.
	 * 
	 * @param value allowed object is {@link Taksa }
	 * 
	 */
	public void setTaksa(Taksa value) {
		this.taksa = value;
	}

}
