//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:05:34 PM CET 
//


package com.ftn.xml.model.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}osnovni_podaci"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}sadrzaj"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}poverenik"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}broj_zalbe"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}ishod"/>
 *       &lt;/sequence>
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="broj" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="vocab" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "osnovniPodaci",
    "sadrzaj",
    "poverenik",
    "brojZalbe",
    "ishod"
})
@XmlRootElement(name = "resenje")
public class Resenje {

    @XmlElement(name = "osnovni_podaci", required = true)
    protected OsnovniPodaci osnovniPodaci;
    @XmlElement(required = true)
    protected Sadrzaj sadrzaj;
    @XmlElement(required = true)
    protected Poverenik poverenik;
    @XmlElement(name = "broj_zalbe", required = true)
    protected BrojZalbe brojZalbe;
    @XmlElement(required = true)
    protected Ishod ishod;
    @XmlAttribute(name = "about", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String about;
    @XmlAttribute(name = "broj", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String broj;
    @XmlAttribute(name = "vocab", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String vocab;

    /**
     * Gets the value of the osnovniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link OsnovniPodaci }
     *     
     */
    public OsnovniPodaci getOsnovniPodaci() {
        return osnovniPodaci;
    }

    /**
     * Sets the value of the osnovniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsnovniPodaci }
     *     
     */
    public void setOsnovniPodaci(OsnovniPodaci value) {
        this.osnovniPodaci = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link Sadrzaj }
     *     
     */
    public Sadrzaj getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sadrzaj }
     *     
     */
    public void setSadrzaj(Sadrzaj value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the poverenik property.
     * 
     * @return
     *     possible object is
     *     {@link Poverenik }
     *     
     */
    public Poverenik getPoverenik() {
        return poverenik;
    }

    /**
     * Sets the value of the poverenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Poverenik }
     *     
     */
    public void setPoverenik(Poverenik value) {
        this.poverenik = value;
    }

    /**
     * Gets the value of the brojZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link BrojZalbe }
     *     
     */
    public BrojZalbe getBrojZalbe() {
        return brojZalbe;
    }

    /**
     * Sets the value of the brojZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrojZalbe }
     *     
     */
    public void setBrojZalbe(BrojZalbe value) {
        this.brojZalbe = value;
    }

    /**
     * Gets the value of the ishod property.
     * 
     * @return
     *     possible object is
     *     {@link Ishod }
     *     
     */
    public Ishod getIshod() {
        return ishod;
    }

    /**
     * Sets the value of the ishod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ishod }
     *     
     */
    public void setIshod(Ishod value) {
        this.ishod = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the broj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroj() {
        return broj;
    }

    /**
     * Sets the value of the broj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroj(String value) {
        this.broj = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab(String value) {
        this.vocab = value;
    }

}
