//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:07:41 PM CET 
//


package com.ftn.xml.model.zahtev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.jaxb.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.jaxb.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Broj }
     * 
     */
    public Broj createBroj() {
        return new Broj();
    }

    /**
     * Create an instance of {@link ListaZahtevaZaPristupInformacijama }
     * 
     */
    public ListaZahtevaZaPristupInformacijama createListaZahtevaZaPristupInformacijama() {
        return new ListaZahtevaZaPristupInformacijama();
    }

    /**
     * Create an instance of {@link ZahtevZaPristupInformacijama }
     * 
     */
    public ZahtevZaPristupInformacijama createZahtevZaPristupInformacijama() {
        return new ZahtevZaPristupInformacijama();
    }

    /**
     * Create an instance of {@link PodaciOOrganu }
     * 
     */
    public PodaciOOrganu createPodaciOOrganu() {
        return new PodaciOOrganu();
    }

    /**
     * Create an instance of {@link Naziv }
     * 
     */
    public Naziv createNaziv() {
        return new Naziv();
    }

    /**
     * Create an instance of {@link Sediste }
     * 
     */
    public Sediste createSediste() {
        return new Sediste();
    }

    /**
     * Create an instance of {@link Sadrzaj }
     * 
     */
    public Sadrzaj createSadrzaj() {
        return new Sadrzaj();
    }

    /**
     * Create an instance of {@link Zahtevi }
     * 
     */
    public Zahtevi createZahtevi() {
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link NaciniDostave }
     * 
     */
    public NaciniDostave createNaciniDostave() {
        return new NaciniDostave();
    }

    /**
     * Create an instance of {@link Nacin }
     * 
     */
    public Nacin createNacin() {
        return new Nacin();
    }

    /**
     * Create an instance of {@link DrugiNacin }
     * 
     */
    public DrugiNacin createDrugiNacin() {
        return new DrugiNacin();
    }

    /**
     * Create an instance of {@link OpisTrazeneInformacije }
     * 
     */
    public OpisTrazeneInformacije createOpisTrazeneInformacije() {
        return new OpisTrazeneInformacije();
    }

    /**
     * Create an instance of {@link Podnozje }
     * 
     */
    public Podnozje createPodnozje() {
        return new Podnozje();
    }

    /**
     * Create an instance of {@link MestoIDatum }
     * 
     */
    public MestoIDatum createMestoIDatum() {
        return new MestoIDatum();
    }

    /**
     * Create an instance of {@link Mesto }
     * 
     */
    public Mesto createMesto() {
        return new Mesto();
    }

    /**
     * Create an instance of {@link DatumZahteva }
     * 
     */
    public DatumZahteva createDatumZahteva() {
        return new DatumZahteva();
    }

    /**
     * Create an instance of {@link InformacijeOTraziocu }
     * 
     */
    public InformacijeOTraziocu createInformacijeOTraziocu() {
        return new InformacijeOTraziocu();
    }

    /**
     * Create an instance of {@link KorisnikEmail }
     * 
     */
    public KorisnikEmail createKorisnikEmail() {
        return new KorisnikEmail();
    }

    /**
     * Create an instance of {@link ImeIPrezime }
     * 
     */
    public ImeIPrezime createImeIPrezime() {
        return new ImeIPrezime();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Ulica }
     * 
     */
    public Ulica createUlica() {
        return new Ulica();
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link Potpis }
     * 
     */
    public Potpis createPotpis() {
        return new Potpis();
    }

}
