//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:57:42 PM CET 
//


package com.ftn.xml.jaxb.zahtev;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.jaxb.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Kontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "kontakt");
    private final static QName _Naziv_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "naziv");
    private final static QName _DrugiNacin_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "drugi_nacin");
    private final static QName _Datum_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "datum");
    private final static QName _Broj_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "broj");
    private final static QName _BrojUlice_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "brojUlice");
    private final static QName _Mesto_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "mesto");
    private final static QName _OpisTrazeneInformacije_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "opis_trazene_informacije");
    private final static QName _ImeIPrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "ime_i_prezime");
    private final static QName _Ulica_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "ulica");
    private final static QName _Naslov_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "naslov");
    private final static QName _Sediste_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "sediste");
    private final static QName _Potpis_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtev", "potpis");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.jaxb.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SadrzajZahteva }
     * 
     */
    public SadrzajZahteva createSadrzajZahteva() {
        return new SadrzajZahteva();
    }

    /**
     * Create an instance of {@link Paragraf }
     * 
     */
    public Paragraf createParagraf() {
        return new Paragraf();
    }

    /**
     * Create an instance of {@link SluzbeniGlasnik }
     * 
     */
    public SluzbeniGlasnik createSluzbeniGlasnik() {
        return new SluzbeniGlasnik();
    }

    /**
     * Create an instance of {@link Brojevi }
     * 
     */
    public Brojevi createBrojevi() {
        return new Brojevi();
    }

    /**
     * Create an instance of {@link Stavke }
     * 
     */
    public Stavke createStavke() {
        return new Stavke();
    }

    /**
     * Create an instance of {@link Stavka }
     * 
     */
    public Stavka createStavka() {
        return new Stavka();
    }

    /**
     * Create an instance of {@link Podstavke }
     * 
     */
    public Podstavke createPodstavke() {
        return new Podstavke();
    }

    /**
     * Create an instance of {@link Podstavka }
     * 
     */
    public Podstavka createPodstavka() {
        return new Podstavka();
    }

    /**
     * Create an instance of {@link Zakon }
     * 
     */
    public Zakon createZakon() {
        return new Zakon();
    }

    /**
     * Create an instance of {@link Podnozje }
     * 
     */
    public Podnozje createPodnozje() {
        return new Podnozje();
    }

    /**
     * Create an instance of {@link MestoIDatum }
     * 
     */
    public MestoIDatum createMestoIDatum() {
        return new MestoIDatum();
    }

    /**
     * Create an instance of {@link InformacijeOTraziocu }
     * 
     */
    public InformacijeOTraziocu createInformacijeOTraziocu() {
        return new InformacijeOTraziocu();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link PodaciOOrganu }
     * 
     */
    public PodaciOOrganu createPodaciOOrganu() {
        return new PodaciOOrganu();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "kontakt")
    public JAXBElement<String> createKontakt(String value) {
        return new JAXBElement<String>(_Kontakt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "naziv")
    public JAXBElement<String> createNaziv(String value) {
        return new JAXBElement<String>(_Naziv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "drugi_nacin")
    public JAXBElement<String> createDrugiNacin(String value) {
        return new JAXBElement<String>(_DrugiNacin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "datum")
    public JAXBElement<XMLGregorianCalendar> createDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Datum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "broj")
    public JAXBElement<String> createBroj(String value) {
        return new JAXBElement<String>(_Broj_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "brojUlice")
    public JAXBElement<BigInteger> createBrojUlice(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojUlice_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "mesto")
    public JAXBElement<String> createMesto(String value) {
        return new JAXBElement<String>(_Mesto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "opis_trazene_informacije")
    public JAXBElement<String> createOpisTrazeneInformacije(String value) {
        return new JAXBElement<String>(_OpisTrazeneInformacije_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "ime_i_prezime")
    public JAXBElement<String> createImeIPrezime(String value) {
        return new JAXBElement<String>(_ImeIPrezime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "ulica")
    public JAXBElement<String> createUlica(String value) {
        return new JAXBElement<String>(_Ulica_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "naslov")
    public JAXBElement<String> createNaslov(String value) {
        return new JAXBElement<String>(_Naslov_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "sediste")
    public JAXBElement<String> createSediste(String value) {
        return new JAXBElement<String>(_Sediste_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtev", name = "potpis")
    public JAXBElement<String> createPotpis(String value) {
        return new JAXBElement<String>(_Potpis_QNAME, String.class, null, value);
    }

}
