//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:57:42 PM CET 
//


package com.ftn.xml.jaxb.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}drugi_nacin" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="nacin" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="otkaceno" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drugiNacin"
})
@XmlRootElement(name = "podstavka")
public class Podstavka {

    @XmlElement(name = "drugi_nacin")
    protected String drugiNacin;
    @XmlAttribute(name = "fusnota")
    protected String fusnota;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "nacin", required = true)
    protected String nacin;
    @XmlAttribute(name = "otkaceno")
    protected Boolean otkaceno;

    /**
     * Gets the value of the drugiNacin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugiNacin() {
        return drugiNacin;
    }

    /**
     * Sets the value of the drugiNacin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugiNacin(String value) {
        this.drugiNacin = value;
    }

    /**
     * Gets the value of the fusnota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFusnota() {
        return fusnota;
    }

    /**
     * Sets the value of the fusnota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFusnota(String value) {
        this.fusnota = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nacin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacin() {
        return nacin;
    }

    /**
     * Sets the value of the nacin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacin(String value) {
        this.nacin = value;
    }

    /**
     * Gets the value of the otkaceno property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOtkaceno() {
        if (otkaceno == null) {
            return false;
        } else {
            return otkaceno;
        }
    }

    /**
     * Sets the value of the otkaceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOtkaceno(Boolean value) {
        this.otkaceno = value;
    }

}
