//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 07:17:12 PM CET 
//


package com.ftn.xml.jaxb.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}podaci_o_organu"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}sadrzaj_zahteva"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}podnozje"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOOrganu",
    "sadrzajZahteva",
    "podnozje"
})
@XmlRootElement(name = "zahtev")
public class Zahtev {

    @XmlElement(name = "podaci_o_organu", required = true)
    protected PodaciOOrganu podaciOOrganu;
    @XmlElement(name = "sadrzaj_zahteva", required = true)
    protected SadrzajZahteva sadrzajZahteva;
    @XmlElement(required = true)
    protected Podnozje podnozje;

    /**
     * Gets the value of the podaciOOrganu property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOOrganu }
     *     
     */
    public PodaciOOrganu getPodaciOOrganu() {
        return podaciOOrganu;
    }

    /**
     * Sets the value of the podaciOOrganu property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOOrganu }
     *     
     */
    public void setPodaciOOrganu(PodaciOOrganu value) {
        this.podaciOOrganu = value;
    }

    /**
     * Gets the value of the sadrzajZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link SadrzajZahteva }
     *     
     */
    public SadrzajZahteva getSadrzajZahteva() {
        return sadrzajZahteva;
    }

    /**
     * Sets the value of the sadrzajZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link SadrzajZahteva }
     *     
     */
    public void setSadrzajZahteva(SadrzajZahteva value) {
        this.sadrzajZahteva = value;
    }

    /**
     * Gets the value of the podnozje property.
     * 
     * @return
     *     possible object is
     *     {@link Podnozje }
     *     
     */
    public Podnozje getPodnozje() {
        return podnozje;
    }

    /**
     * Sets the value of the podnozje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Podnozje }
     *     
     */
    public void setPodnozje(Podnozje value) {
        this.podnozje = value;
    }

}
