package com.ftn.xml.soap.resenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ftn.xml.model.resenje.ObjectFactory;
import com.ftn.xml.model.resenje.Resenje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T19:04:50.480+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://ftn.uns.ac.rs/resenje", name = "ResenjeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ResenjeServicePortType {

    @WebMethod(action = "http://ftn.uns.ac.rs/resenje/ws/dodajResenje")
    @WebResult(name = "res", targetNamespace = "http://ftn.uns.ac.rs/resenje", partName = "res")
    public java.lang.String dodajResenje(
        @WebParam(partName = "resenje", name = "resenje")
        Resenje resenje
    );
}
