
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ftn.xml.soap.resenje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ftn.xml.model.resenje.Resenje;
import com.ftn.xml.service.ResenjeService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T19:04:50.469+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ResenjeService",
                      portName = "ResenjeServiceSoapBinding",
                      targetNamespace = "http://ftn.uns.ac.rs/resenje",
                      wsdlLocation = "src/main/resources/static/wsdl/resenje.wsdl",
                      endpointInterface = "com.ftn.xml.soap.resenje.ResenjeServicePortType")
@Service                      
public class ResenjeServiceSoapBindingImpl implements ResenjeServicePortType {

    private static final Logger LOG = Logger.getLogger(ResenjeServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.resenje.ResenjeServicePortType#dodajResenje(rs.ac.uns.ftn.resenje.Resenje resenje)*
     */
    
    @Autowired
    private ResenjeService resenjeService;
    
    public java.lang.String dodajResenje(Resenje resenje) { 
        LOG.info("Executing operation dodajResenje");
        System.out.println(resenje);
        try {
        	this.resenjeService.dodajResenje(resenje);
            java.lang.String _return = "OK";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
