//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.21 at 12:10:39 PM CET 
//


package com.ftn.xml.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}nacin_posta"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}nacin_e_posta"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}nacin_faks"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}nacin_drugi"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nacinPosta",
    "nacinEPosta",
    "nacinFaks",
    "nacinDrugi"
})
@XmlRootElement(name = "nacini_dostave")
public class NaciniDostave {

    @XmlElement(name = "nacin_posta", required = true)
    protected NacinPosta nacinPosta;
    @XmlElement(name = "nacin_e_posta", required = true)
    protected NacinEPosta nacinEPosta;
    @XmlElement(name = "nacin_faks", required = true)
    protected NacinFaks nacinFaks;
    @XmlElement(name = "nacin_drugi", required = true)
    protected NacinDrugi nacinDrugi;

    /**
     * Gets the value of the nacinPosta property.
     * 
     * @return
     *     possible object is
     *     {@link NacinPosta }
     *     
     */
    public NacinPosta getNacinPosta() {
        return nacinPosta;
    }

    /**
     * Sets the value of the nacinPosta property.
     * 
     * @param value
     *     allowed object is
     *     {@link NacinPosta }
     *     
     */
    public void setNacinPosta(NacinPosta value) {
        this.nacinPosta = value;
    }

    /**
     * Gets the value of the nacinEPosta property.
     * 
     * @return
     *     possible object is
     *     {@link NacinEPosta }
     *     
     */
    public NacinEPosta getNacinEPosta() {
        return nacinEPosta;
    }

    /**
     * Sets the value of the nacinEPosta property.
     * 
     * @param value
     *     allowed object is
     *     {@link NacinEPosta }
     *     
     */
    public void setNacinEPosta(NacinEPosta value) {
        this.nacinEPosta = value;
    }

    /**
     * Gets the value of the nacinFaks property.
     * 
     * @return
     *     possible object is
     *     {@link NacinFaks }
     *     
     */
    public NacinFaks getNacinFaks() {
        return nacinFaks;
    }

    /**
     * Sets the value of the nacinFaks property.
     * 
     * @param value
     *     allowed object is
     *     {@link NacinFaks }
     *     
     */
    public void setNacinFaks(NacinFaks value) {
        this.nacinFaks = value;
    }

    /**
     * Gets the value of the nacinDrugi property.
     * 
     * @return
     *     possible object is
     *     {@link NacinDrugi }
     *     
     */
    public NacinDrugi getNacinDrugi() {
        return nacinDrugi;
    }

    /**
     * Sets the value of the nacinDrugi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NacinDrugi }
     *     
     */
    public void setNacinDrugi(NacinDrugi value) {
        this.nacinDrugi = value;
    }

}
