//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.21 at 12:10:39 PM CET 
//


package com.ftn.xml.model.zahtev;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}zahtev_za_dostavu"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}zahtev_za_kopiju"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}zahtev_za_obavestenje"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}zahtev_za_uvid"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "zahtevi")
public class Zahtevi {

    @XmlElementRefs({
        @XmlElementRef(name = "zahtev_za_dostavu", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = ZahtevZaDostavu.class, required = false),
        @XmlElementRef(name = "zahtev_za_kopiju", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = ZahtevZaKopiju.class, required = false),
        @XmlElementRef(name = "zahtev_za_uvid", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = ZahtevZaUvid.class, required = false),
        @XmlElementRef(name = "zahtev_za_obavestenje", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = ZahtevZaObavestenje.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZahtevZaUvid }
     * {@link ZahtevZaObavestenje }
     * {@link String }
     * {@link ZahtevZaDostavu }
     * {@link ZahtevZaKopiju }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
