//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 04:48:37 PM CET 
//


package com.ftn.xml.model.odgovor_zahtev_za_izjasnjenje;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/izjasnjenje/odgovor}odgovor_zahtev_za_izjasnjenje" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "odgovorZahtevZaIzjasnjenje"
})
@XmlRootElement(name = "odgovori_zahtev_za_izjasnjenje")
public class OdgovoriZahtevZaIzjasnjenje {

    @XmlElement(name = "odgovor_zahtev_za_izjasnjenje", required = true)
    protected List<OdgovorZahtevZaIzjasnjenje> odgovorZahtevZaIzjasnjenje;

    /**
     * Gets the value of the odgovorZahtevZaIzjasnjenje property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the odgovorZahtevZaIzjasnjenje property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOdgovorZahtevZaIzjasnjenje().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OdgovorZahtevZaIzjasnjenje }
     * 
     * 
     */
    public List<OdgovorZahtevZaIzjasnjenje> getOdgovorZahtevZaIzjasnjenje() {
        if (odgovorZahtevZaIzjasnjenje == null) {
            odgovorZahtevZaIzjasnjenje = new ArrayList<OdgovorZahtevZaIzjasnjenje>();
        }
        return this.odgovorZahtevZaIzjasnjenje;
    }

}
