//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 05:00:05 PM CET 
//


package com.ftn.xml.model.zahtev_za_izjasnjenje_odluka;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.ftn.xml.model.zalba_na_odluku.BrojZahteva;
import com.ftn.xml.model.zalba_na_odluku.BrojZalbe;
import com.ftn.xml.model.zalba_na_odluku.DatumOdbijenogZahteva;
import com.ftn.xml.model.zalba_na_odluku.DatumZakljuckaZalbe;
import com.ftn.xml.model.zalba_na_odluku.DrugiPodaciZaKontakt;
import com.ftn.xml.model.zalba_na_odluku.GodinaZalbe;
import com.ftn.xml.model.zalba_na_odluku.KorisnikEmail;
import com.ftn.xml.model.zalba_na_odluku.MestoZakljuckaZalbe;
import com.ftn.xml.model.zalba_na_odluku.Naziv;
import com.ftn.xml.model.zalba_na_odluku.OdlukaOrganaVlasti;
import com.ftn.xml.model.zalba_na_odluku.OsnovniPodaci;
import com.ftn.xml.model.zalba_na_odluku.PodaciOOrganu;
import com.ftn.xml.model.zalba_na_odluku.PodaciOZaliocu;
import com.ftn.xml.model.zalba_na_odluku.Podnozje;
import com.ftn.xml.model.zalba_na_odluku.PotpisZalioca;
import com.ftn.xml.model.zalba_na_odluku.Sadrzaj;
import com.ftn.xml.model.zalba_na_odluku.ZalbaNaOdluku;
import com.ftn.xml.model.zalba_na_odluku.ZaliocAdresa;
import com.ftn.xml.model.zalba_na_odluku.ZaliocIme;
import com.ftn.xml.model.zalba_na_odluku.ZaliocNazivZalbe;
import com.ftn.xml.model.zalba_na_odluku.ZaliocPrezime;
import com.ftn.xml.model.zalba_na_odluku.ZaliocSediste;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.model.zahtev_za_izjasnjenje_odluka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Vreme_QNAME = new QName("http://ftn.uns.ac.rs/izjasnjenje/odluka", "vreme");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.model.zahtev_za_izjasnjenje_odluka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZaliocAdresa }
     * 
     */
    public ZaliocAdresa createZaliocAdresa() {
        return new ZaliocAdresa();
    }

    /**
     * Create an instance of {@link PodaciOZaliocu }
     * 
     */
    public PodaciOZaliocu createPodaciOZaliocu() {
        return new PodaciOZaliocu();
    }

    /**
     * Create an instance of {@link KorisnikEmail }
     * 
     */
    public KorisnikEmail createKorisnikEmail() {
        return new KorisnikEmail();
    }

    /**
     * Create an instance of {@link ZaliocIme }
     * 
     */
    public ZaliocIme createZaliocIme() {
        return new ZaliocIme();
    }

    /**
     * Create an instance of {@link ZaliocPrezime }
     * 
     */
    public ZaliocPrezime createZaliocPrezime() {
        return new ZaliocPrezime();
    }

    /**
     * Create an instance of {@link ZaliocNazivZalbe }
     * 
     */
    public ZaliocNazivZalbe createZaliocNazivZalbe() {
        return new ZaliocNazivZalbe();
    }

    /**
     * Create an instance of {@link ZaliocSediste }
     * 
     */
    public ZaliocSediste createZaliocSediste() {
        return new ZaliocSediste();
    }

    /**
     * Create an instance of {@link DrugiPodaciZaKontakt }
     * 
     */
    public DrugiPodaciZaKontakt createDrugiPodaciZaKontakt() {
        return new DrugiPodaciZaKontakt();
    }

    /**
     * Create an instance of {@link PotpisZalioca }
     * 
     */
    public PotpisZalioca createPotpisZalioca() {
        return new PotpisZalioca();
    }

    /**
     * Create an instance of {@link MestoZakljuckaZalbe }
     * 
     */
    public MestoZakljuckaZalbe createMestoZakljuckaZalbe() {
        return new MestoZakljuckaZalbe();
    }

    /**
     * Create an instance of {@link Podnozje }
     * 
     */
    public Podnozje createPodnozje() {
        return new Podnozje();
    }

    /**
     * Create an instance of {@link DatumZakljuckaZalbe }
     * 
     */
    public DatumZakljuckaZalbe createDatumZakljuckaZalbe() {
        return new DatumZakljuckaZalbe();
    }

    /**
     * Create an instance of {@link ZahteviZaIzjasnjenjeOdluka }
     * 
     */
    public ZahteviZaIzjasnjenjeOdluka createZahteviZaIzjasnjenjeOdluka() {
        return new ZahteviZaIzjasnjenjeOdluka();
    }

    /**
     * Create an instance of {@link ZahtevZaIzjasnjenjeOdluka }
     * 
     */
    public ZahtevZaIzjasnjenjeOdluka createZahtevZaIzjasnjenjeOdluka() {
        return new ZahtevZaIzjasnjenjeOdluka();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku }
     * 
     */
    public ZalbaNaOdluku createZalbaNaOdluku() {
        return new ZalbaNaOdluku();
    }

    /**
     * Create an instance of {@link OsnovniPodaci }
     * 
     */
    public OsnovniPodaci createOsnovniPodaci() {
        return new OsnovniPodaci();
    }

    /**
     * Create an instance of {@link PodaciOOrganu }
     * 
     */
    public PodaciOOrganu createPodaciOOrganu() {
        return new PodaciOOrganu();
    }

    /**
     * Create an instance of {@link Naziv }
     * 
     */
    public Naziv createNaziv() {
        return new Naziv();
    }

    /**
     * Create an instance of {@link Sadrzaj }
     * 
     */
    public Sadrzaj createSadrzaj() {
        return new Sadrzaj();
    }

    /**
     * Create an instance of {@link BrojZalbe }
     * 
     */
    public BrojZalbe createBrojZalbe() {
        return new BrojZalbe();
    }

    /**
     * Create an instance of {@link GodinaZalbe }
     * 
     */
    public GodinaZalbe createGodinaZalbe() {
        return new GodinaZalbe();
    }

    /**
     * Create an instance of {@link DatumOdbijenogZahteva }
     * 
     */
    public DatumOdbijenogZahteva createDatumOdbijenogZahteva() {
        return new DatumOdbijenogZahteva();
    }

    /**
     * Create an instance of {@link OdlukaOrganaVlasti }
     * 
     */
    public OdlukaOrganaVlasti createOdlukaOrganaVlasti() {
        return new OdlukaOrganaVlasti();
    }

    /**
     * Create an instance of {@link BrojZahteva }
     * 
     */
    public BrojZahteva createBrojZahteva() {
        return new BrojZahteva();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/izjasnjenje/odluka", name = "vreme")
    public JAXBElement<String> createVreme(String value) {
        return new JAXBElement<String>(_Vreme_QNAME, String.class, null, value);
    }

}
