//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 05:00:05 PM CET 
//


package com.ftn.xml.model.zahtev_za_izjasnjenje_odluka;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.ftn.xml.model.zalba_na_odluku.ZalbaNaOdluku;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/izjasnjenje/odluka}zalba_na_odluku"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/izjasnjenje/odluka}vreme"/>
 *       &lt;/sequence>
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zalbaNaOdluku",
    "vreme"
})
@XmlRootElement(name = "zahtev_za_izjasnjenje_odluka")
public class ZahtevZaIzjasnjenjeOdluka {

    @XmlElement(name = "zalba_na_odluku", required = true)
    protected ZalbaNaOdluku zalbaNaOdluku;
    @XmlElement(required = true)
    protected String vreme;
    @XmlAttribute(name = "about", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String about;

    /**
     * Gets the value of the zalbaNaOdluku property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaNaOdluku }
     *     
     */
    public ZalbaNaOdluku getZalbaNaOdluku() {
        return zalbaNaOdluku;
    }

    /**
     * Sets the value of the zalbaNaOdluku property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaNaOdluku }
     *     
     */
    public void setZalbaNaOdluku(ZalbaNaOdluku value) {
        this.zalbaNaOdluku = value;
    }

    /**
     * Gets the value of the vreme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVreme() {
        return vreme;
    }

    /**
     * Sets the value of the vreme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVreme(String value) {
        this.vreme = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

}
