package com.ftn.xml.soap.zahtev_za_izjasnjenje_cutnja;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ftn.xml.model.zalba_cutanje.ObjectFactory;
import com.ftn.xml.model.zalba_cutanje.ZalbaCutanje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T19:23:12.840+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://ftn.uns.ac.rs/zalba_cutanje", name = "ZahtevZaIzjasnjenjeCutnjaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZahtevZaIzjasnjenjeCutnjaServicePortType {

    @WebMethod(operationName = "dodajZahtevZaIzjasnjenjeCutnje", action = "http://www.ftn.uns.ac.rs/zahtev_za_izjasnjenje_cutnja/ws/dodajZahtevZaIzjasnjenjeCutnje")
    @WebResult(name = "ok", targetNamespace = "http://ftn.uns.ac.rs/zalba_cutanje", partName = "ok")
    public java.lang.String dodajZahtevZaIzjasnjenjeCutnje(
        @WebParam(partName = "zalba_cutanje", name = "zalba_cutanje")
        ZalbaCutanje zalbaCutanje
    );

    @WebMethod(action = "http://www.ftn.uns.ac.rs/zahtev_za_izjasnjenje_cutnja/ws/izbrisiZahtevZaIzjasnjenjeCutanje")
    @WebResult(name = "ok", targetNamespace = "http://ftn.uns.ac.rs/zalba_cutanje", partName = "ok")
    public java.lang.String izbrisiZahtevZaIzjasnjenjeCutanje(
        @WebParam(partName = "id_zalbe", name = "id_zalbe")
        java.lang.String idZalbe
    );
}
