//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:12:56 PM CET 
//

package com.ftn.xml.model.zalba_na_odluku;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.ftn.xml.jaxb.zalba_na_odluku package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: com.ftn.xml.jaxb.zalba_na_odluku
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ZaliocAdresa }
	 * 
	 */
	public ZaliocAdresa createZaliocAdresa() {
		return new ZaliocAdresa();
	}

	/**
	 * Create an instance of {@link ListaZalbiNaOdluku }
	 * 
	 */
	public ListaZalbiNaOdluku createListaZalbiNaOdluku() {
		return new ListaZalbiNaOdluku();
	}

	/**
	 * Create an instance of {@link ZalbaNaOdluku }
	 * 
	 */
	public ZalbaNaOdluku createZalbaNaOdluku() {
		return new ZalbaNaOdluku();
	}

	/**
	 * Create an instance of {@link OsnovniPodaci }
	 * 
	 */
	public OsnovniPodaci createOsnovniPodaci() {
		return new OsnovniPodaci();
	}

	/**
	 * Create an instance of {@link PodaciOZaliocu }
	 * 
	 */
	public PodaciOZaliocu createPodaciOZaliocu() {
		return new PodaciOZaliocu();
	}

	/**
	 * Create an instance of {@link KorisnikEmail }
	 * 
	 */
	public KorisnikEmail createKorisnikEmail() {
		return new KorisnikEmail();
	}

	/**
	 * Create an instance of {@link ZaliocIme }
	 * 
	 */
	public ZaliocIme createZaliocIme() {
		return new ZaliocIme();
	}

	/**
	 * Create an instance of {@link ZaliocPrezime }
	 * 
	 */
	public ZaliocPrezime createZaliocPrezime() {
		return new ZaliocPrezime();
	}

	/**
	 * Create an instance of {@link ZaliocNazivZalbe }
	 * 
	 */
	public ZaliocNazivZalbe createZaliocNazivZalbe() {
		return new ZaliocNazivZalbe();
	}

	/**
	 * Create an instance of {@link ZaliocSediste }
	 * 
	 */
	public ZaliocSediste createZaliocSediste() {
		return new ZaliocSediste();
	}

	/**
	 * Create an instance of {@link DrugiPodaciZaKontakt }
	 * 
	 */
	public DrugiPodaciZaKontakt createDrugiPodaciZaKontakt() {
		return new DrugiPodaciZaKontakt();
	}

	/**
	 * Create an instance of {@link PotpisZalioca }
	 * 
	 */
	public PotpisZalioca createPotpisZalioca() {
		return new PotpisZalioca();
	}

	/**
	 * Create an instance of {@link PodaciOOrganu }
	 * 
	 */
	public PodaciOOrganu createPodaciOOrganu() {
		return new PodaciOOrganu();
	}

	/**
	 * Create an instance of {@link Naziv }
	 * 
	 */
	public Naziv createNaziv() {
		return new Naziv();
	}

	/**
	 * Create an instance of {@link Sadrzaj }
	 * 
	 */
	public Sadrzaj createSadrzaj() {
		return new Sadrzaj();
	}

	/**
	 * Create an instance of {@link BrojZalbe }
	 * 
	 */
	public BrojZalbe createBrojZalbe() {
		return new BrojZalbe();
	}

	/**
	 * Create an instance of {@link GodinaZalbe }
	 * 
	 */
	public GodinaZalbe createGodinaZalbe() {
		return new GodinaZalbe();
	}

	/**
	 * Create an instance of {@link DatumOdbijenogZahteva }
	 * 
	 */
	public DatumOdbijenogZahteva createDatumOdbijenogZahteva() {
		return new DatumOdbijenogZahteva();
	}

	/**
	 * Create an instance of {@link OdlukaOrganaVlasti }
	 * 
	 */
	public OdlukaOrganaVlasti createOdlukaOrganaVlasti() {
		return new OdlukaOrganaVlasti();
	}

	/**
	 * Create an instance of {@link Podnozje }
	 * 
	 */
	public Podnozje createPodnozje() {
		return new Podnozje();
	}

	/**
	 * Create an instance of {@link MestoZakljuckaZalbe }
	 * 
	 */
	public MestoZakljuckaZalbe createMestoZakljuckaZalbe() {
		return new MestoZakljuckaZalbe();
	}

	/**
	 * Create an instance of {@link DatumZakljuckaZalbe }
	 * 
	 */
	public DatumZakljuckaZalbe createDatumZakljuckaZalbe() {
		return new DatumZakljuckaZalbe();
	}

	/**
	 * Create an instance of {@link BrojZahteva }
	 * 
	 */
	public BrojZahteva createBrojZahteva() {
		return new BrojZahteva();
	}

}
