//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 07:05:34 PM CET 
//


package com.ftn.xml.model.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}trazeni_dokument"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}tekst_resenja"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trazeniDokument",
    "tekstResenja"
})
@XmlRootElement(name = "doneto_resenje")
public class DonetoResenje {

    @XmlElement(name = "trazeni_dokument", required = true)
    protected TrazeniDokument trazeniDokument;
    @XmlElement(name = "tekst_resenja", required = true)
    protected String tekstResenja;

    /**
     * Gets the value of the trazeniDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TrazeniDokument }
     *     
     */
    public TrazeniDokument getTrazeniDokument() {
        return trazeniDokument;
    }

    /**
     * Sets the value of the trazeniDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrazeniDokument }
     *     
     */
    public void setTrazeniDokument(TrazeniDokument value) {
        this.trazeniDokument = value;
    }

    /**
     * Gets the value of the tekstResenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekstResenja() {
        return tekstResenja;
    }

    /**
     * Sets the value of the tekstResenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekstResenja(String value) {
        this.tekstResenja = value;
    }

}
