//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 12:50:28 PM CET 
//

package com.ftn.xml.model.brojac;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/brojac}brojac_zahtev"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "brojacZahtev", "brojacObavestenje" })
@XmlRootElement(name = "brojac")
public class Brojac {

	@XmlElement(name = "brojac_zahtev", required = true)
	protected int brojacZahtev;

	@XmlElement(name = "brojac_obavestenje", required = true)
	protected int brojacObavestenje;

	/**
	 * Gets the value of the brojacZahtev property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public int getBrojacZahtev() {
		return brojacZahtev;
	}

	public int getBrojacObavestenje() {
		return brojacObavestenje;
	}

	public void setBrojacObavestenje(int brojacObavestenje) {
		this.brojacObavestenje = brojacObavestenje;
	}

	/**
	 * Sets the value of the brojacZahtev property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setBrojacZahtev(int value) {
		this.brojacZahtev = value;
	}

}
