package com.ftn.xml.soap.izvestaj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ftn.xml.model.izvestaj.Izvestaj;
import com.ftn.xml.model.izvestaj.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T19:20:32.159+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/izvestaj", name = "IzvestajServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IzvestajServicePortType {

    @WebMethod(action = "http://www.ftn.uns.ac.rs/izvestaj/ws/dodajIzvestaj")
    @WebResult(name = "res", targetNamespace = "http://www.ftn.uns.ac.rs/izvestaj", partName = "res")
    public java.lang.String dodajIzvestaj(
        @WebParam(partName = "izvestaj", name = "izvestaj")
        Izvestaj izvestaj
    );
}
