
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ftn.xml.soap.izvestaj;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ftn.xml.model.izvestaj.Izvestaj;
import com.ftn.xml.service.IzvestajService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T19:20:32.151+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "IzvestajService",
                      portName = "IzvestajServiceSoapBinding",
                      targetNamespace = "http://www.ftn.uns.ac.rs/izvestaj",
                      wsdlLocation = "src/main/resources/static/wsdl/izvestaj.wsdl",
                      endpointInterface = "com.ftn.xml.soap.izvestaj.IzvestajServicePortType")
@Service                      
public class IzvestajServiceSoapBindingImpl implements IzvestajServicePortType {

    private static final Logger LOG = Logger.getLogger(IzvestajServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.izvestaj.IzvestajServicePortType#dodajIzvestaj(rs.ac.uns.ftn.izvestaj.Izvestaj izvestaj)*
     */
    
    @Autowired
    private IzvestajService service;
    
    public java.lang.String dodajIzvestaj(Izvestaj izvestaj) { 
        LOG.info("Executing operation dodajIzvestaj");
        System.out.println(izvestaj);
        try {
        	this.service.dodajIzvestaj(izvestaj);
            java.lang.String _return = "OK";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
