//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 10:56:50 PM CET 
//


package com.ftn.xml.model.zalba_cutanje;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.model.zalba_cutanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DrugiPodaciZaKontakt_QNAME = new QName("http://ftn.uns.ac.rs/zalba_cutanje", "drugi_podaci_za_kontakt");
    private final static QName _DatumZahteva_QNAME = new QName("http://ftn.uns.ac.rs/zalba_cutanje", "datum_zahteva");
    private final static QName _PodaciOZahtevuIInformacijama_QNAME = new QName("http://ftn.uns.ac.rs/zalba_cutanje", "podaci_o_zahtevu_i_informacijama");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.model.zalba_cutanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Razlog }
     * 
     */
    public Razlog createRazlog() {
        return new Razlog();
    }

    /**
     * Create an instance of {@link Broj }
     * 
     */
    public Broj createBroj() {
        return new Broj();
    }

    /**
     * Create an instance of {@link DatumZalbe }
     * 
     */
    public DatumZalbe createDatumZalbe() {
        return new DatumZalbe();
    }

    /**
     * Create an instance of {@link MestoIDatum }
     * 
     */
    public MestoIDatum createMestoIDatum() {
        return new MestoIDatum();
    }

    /**
     * Create an instance of {@link Mesto }
     * 
     */
    public Mesto createMesto() {
        return new Mesto();
    }

    /**
     * Create an instance of {@link RazloziZalbe }
     * 
     */
    public RazloziZalbe createRazloziZalbe() {
        return new RazloziZalbe();
    }

    /**
     * Create an instance of {@link Zaglavlje }
     * 
     */
    public Zaglavlje createZaglavlje() {
        return new Zaglavlje();
    }

    /**
     * Create an instance of {@link PrimalacZalbe }
     * 
     */
    public PrimalacZalbe createPrimalacZalbe() {
        return new PrimalacZalbe();
    }

    /**
     * Create an instance of {@link NazivPrimaoca }
     * 
     */
    public NazivPrimaoca createNazivPrimaoca() {
        return new NazivPrimaoca();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Ulica }
     * 
     */
    public Ulica createUlica() {
        return new Ulica();
    }

    /**
     * Create an instance of {@link BrojZahteva }
     * 
     */
    public BrojZahteva createBrojZahteva() {
        return new BrojZahteva();
    }

    /**
     * Create an instance of {@link Sadrzaj }
     * 
     */
    public Sadrzaj createSadrzaj() {
        return new Sadrzaj();
    }

    /**
     * Create an instance of {@link NazivOrgana }
     * 
     */
    public NazivOrgana createNazivOrgana() {
        return new NazivOrgana();
    }

    /**
     * Create an instance of {@link ListaZalbiCutanje }
     * 
     */
    public ListaZalbiCutanje createListaZalbiCutanje() {
        return new ListaZalbiCutanje();
    }

    /**
     * Create an instance of {@link ZalbaCutanje }
     * 
     */
    public ZalbaCutanje createZalbaCutanje() {
        return new ZalbaCutanje();
    }

    /**
     * Create an instance of {@link Podnozje }
     * 
     */
    public Podnozje createPodnozje() {
        return new Podnozje();
    }

    /**
     * Create an instance of {@link PodnosilacZalbe }
     * 
     */
    public PodnosilacZalbe createPodnosilacZalbe() {
        return new PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link KorisnikEmail }
     * 
     */
    public KorisnikEmail createKorisnikEmail() {
        return new KorisnikEmail();
    }

    /**
     * Create an instance of {@link ImeIPrezime }
     * 
     */
    public ImeIPrezime createImeIPrezime() {
        return new ImeIPrezime();
    }

    /**
     * Create an instance of {@link Potpis }
     * 
     */
    public Potpis createPotpis() {
        return new Potpis();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/zalba_cutanje", name = "drugi_podaci_za_kontakt")
    public JAXBElement<String> createDrugiPodaciZaKontakt(String value) {
        return new JAXBElement<String>(_DrugiPodaciZaKontakt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/zalba_cutanje", name = "datum_zahteva")
    public JAXBElement<String> createDatumZahteva(String value) {
        return new JAXBElement<String>(_DatumZahteva_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/zalba_cutanje", name = "podaci_o_zahtevu_i_informacijama")
    public JAXBElement<String> createPodaciOZahtevuIInformacijama(String value) {
        return new JAXBElement<String>(_PodaciOZahtevuIInformacijama_QNAME, String.class, null, value);
    }

}
