//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 07:38:13 PM CET 
//


package com.ftn.xml.jaxb.obavestenje;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.jaxb.obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Naslov_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "naslov");
    private final static QName _Ulica_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "ulica");
    private final static QName _Sediste_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "sediste");
    private final static QName _BrojKancelarije_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "broj_kancelarije");
    private final static QName _Cena_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "cena");
    private final static QName _Grad_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "grad");
    private final static QName _ImeIPrezime_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "ime_i_prezime");
    private final static QName _OpisTrazeneInformacije_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "opis_trazene_informacije");
    private final static QName _Datum_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "datum");
    private final static QName _Broj_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "broj");
    private final static QName _Obavestenje_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "obavestenje");
    private final static QName _Sat_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "sat");
    private final static QName _Naziv_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "naziv");
    private final static QName _BrojPredmeta_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "broj_predmeta");
    private final static QName _Godina_QNAME = new QName("http://ftn.uns.ac.rs/obavestenje", "godina");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.jaxb.obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PotpisOvlascenogLica }
     * 
     */
    public PotpisOvlascenogLica createPotpisOvlascenogLica() {
        return new PotpisOvlascenogLica();
    }

    /**
     * Create an instance of {@link TObavestenje }
     * 
     */
    public TObavestenje createTObavestenje() {
        return new TObavestenje();
    }

    /**
     * Create an instance of {@link TeloObavestenja }
     * 
     */
    public TeloObavestenja createTeloObavestenja() {
        return new TeloObavestenja();
    }

    /**
     * Create an instance of {@link Paragraf }
     * 
     */
    public Paragraf createParagraf() {
        return new Paragraf();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link SluzbeniGlasnik }
     * 
     */
    public SluzbeniGlasnik createSluzbeniGlasnik() {
        return new SluzbeniGlasnik();
    }

    /**
     * Create an instance of {@link Zakon }
     * 
     */
    public Zakon createZakon() {
        return new Zakon();
    }

    /**
     * Create an instance of {@link ZiroRacun }
     * 
     */
    public ZiroRacun createZiroRacun() {
        return new ZiroRacun();
    }

    /**
     * Create an instance of {@link Podnozje }
     * 
     */
    public Podnozje createPodnozje() {
        return new Podnozje();
    }

    /**
     * Create an instance of {@link Dostavljeno }
     * 
     */
    public Dostavljeno createDostavljeno() {
        return new Dostavljeno();
    }

    /**
     * Create an instance of {@link Lice }
     * 
     */
    public Lice createLice() {
        return new Lice();
    }

    /**
     * Create an instance of {@link PodaciOOrganu }
     * 
     */
    public PodaciOOrganu createPodaciOOrganu() {
        return new PodaciOOrganu();
    }

    /**
     * Create an instance of {@link OsnovniPodaci }
     * 
     */
    public OsnovniPodaci createOsnovniPodaci() {
        return new OsnovniPodaci();
    }

    /**
     * Create an instance of {@link PodaciOPodnosiocu }
     * 
     */
    public PodaciOPodnosiocu createPodaciOPodnosiocu() {
        return new PodaciOPodnosiocu();
    }

    /**
     * Create an instance of {@link Sadrzaj }
     * 
     */
    public Sadrzaj createSadrzaj() {
        return new Sadrzaj();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "naslov")
    public JAXBElement<String> createNaslov(String value) {
        return new JAXBElement<String>(_Naslov_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "ulica")
    public JAXBElement<String> createUlica(String value) {
        return new JAXBElement<String>(_Ulica_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "sediste")
    public JAXBElement<String> createSediste(String value) {
        return new JAXBElement<String>(_Sediste_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "broj_kancelarije")
    public JAXBElement<BigInteger> createBrojKancelarije(BigInteger value) {
        return new JAXBElement<BigInteger>(_BrojKancelarije_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "cena")
    public JAXBElement<Float> createCena(Float value) {
        return new JAXBElement<Float>(_Cena_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "grad")
    public JAXBElement<String> createGrad(String value) {
        return new JAXBElement<String>(_Grad_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "ime_i_prezime")
    public JAXBElement<String> createImeIPrezime(String value) {
        return new JAXBElement<String>(_ImeIPrezime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "opis_trazene_informacije")
    public JAXBElement<String> createOpisTrazeneInformacije(String value) {
        return new JAXBElement<String>(_OpisTrazeneInformacije_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "datum")
    public JAXBElement<XMLGregorianCalendar> createDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Datum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "broj")
    public JAXBElement<BigInteger> createBroj(BigInteger value) {
        return new JAXBElement<BigInteger>(_Broj_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TObavestenje }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "obavestenje")
    public JAXBElement<TObavestenje> createObavestenje(TObavestenje value) {
        return new JAXBElement<TObavestenje>(_Obavestenje_QNAME, TObavestenje.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "sat")
    public JAXBElement<XMLGregorianCalendar> createSat(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Sat_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "naziv")
    public JAXBElement<String> createNaziv(String value) {
        return new JAXBElement<String>(_Naziv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "broj_predmeta")
    public JAXBElement<String> createBrojPredmeta(String value) {
        return new JAXBElement<String>(_BrojPredmeta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/obavestenje", name = "godina")
    public JAXBElement<Integer> createGodina(Integer value) {
        return new JAXBElement<Integer>(_Godina_QNAME, Integer.class, null, value);
    }

}
