//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:03:27 PM CET 
//


package com.ftn.xml.jaxb.obavestenje;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}adresa"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}datum"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}broj_kancelarije"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}cena"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}godina"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}opis_trazene_informacije"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}sat"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}sluzbeni_glasnik"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}zakon"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}ziro_racun"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "paragraf")
public class Paragraf {

    @XmlElementRefs({
        @XmlElementRef(name = "godina", namespace = "http://ftn.uns.ac.rs/obavestenje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ziro_racun", namespace = "http://ftn.uns.ac.rs/obavestenje", type = ZiroRacun.class, required = false),
        @XmlElementRef(name = "cena", namespace = "http://ftn.uns.ac.rs/obavestenje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datum", namespace = "http://ftn.uns.ac.rs/obavestenje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "broj_kancelarije", namespace = "http://ftn.uns.ac.rs/obavestenje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sluzbeni_glasnik", namespace = "http://ftn.uns.ac.rs/obavestenje", type = SluzbeniGlasnik.class, required = false),
        @XmlElementRef(name = "opis_trazene_informacije", namespace = "http://ftn.uns.ac.rs/obavestenje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "zakon", namespace = "http://ftn.uns.ac.rs/obavestenje", type = Zakon.class, required = false),
        @XmlElementRef(name = "sat", namespace = "http://ftn.uns.ac.rs/obavestenje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "adresa", namespace = "http://ftn.uns.ac.rs/obavestenje", type = Adresa.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link ZiroRacun }
     * {@link JAXBElement }{@code <}{@link Float }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link String }
     * {@link SluzbeniGlasnik }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Zakon }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link Adresa }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
