//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 08:03:27 PM CET 
//


package com.ftn.xml.jaxb.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}naslov"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/obavestenje}telo_obavestenja"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naslov",
    "teloObavestenja"
})
@XmlRootElement(name = "sadrzaj")
public class Sadrzaj {

    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(name = "telo_obavestenja", required = true)
    protected TeloObavestenja teloObavestenja;

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the teloObavestenja property.
     * 
     * @return
     *     possible object is
     *     {@link TeloObavestenja }
     *     
     */
    public TeloObavestenja getTeloObavestenja() {
        return teloObavestenja;
    }

    /**
     * Sets the value of the teloObavestenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeloObavestenja }
     *     
     */
    public void setTeloObavestenja(TeloObavestenja value) {
        this.teloObavestenja = value;
    }

}
