SELECT ?obavestenje FROM <%s>
WHERE {
  ?obavestenje <http://www.ftn.uns.ac.rs/rdf/examples/predicate/br_predmeta> %s .
  ?obavestenje <http://www.ftn.uns.ac.rs/rdf/examples/predicate/ime_podnosioca> %s .
}