//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:58:40 PM CET 
//


package com.ftn.xml.model.zahtev_za_izjasnjenje_cutanje;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.ftn.xml.model.zalba_cutanje.ZalbaCutanje;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/izjasnjenje/cutanje}zahtev_za_izjasnjenje_cutanje" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zahtevZaIzjasnjenjeCutanje"
})
@XmlRootElement(name = "zahtevi_za_izjasnjenje_cutanje")
public class ZahteviZaIzjasnjenjeCutanje {

    @XmlElement(name = "zalba_cutanje", required = true)
    protected List<ZalbaCutanje> zalbaCutanje;

    /**
     * Gets the value of the zahtevZaIzjasnjenjeCutanje property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zahtevZaIzjasnjenjeCutanje property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZahtevZaIzjasnjenjeCutanje().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZahtevZaIzjasnjenjeCutanje }
     * 
     * 
     */
    public List<ZalbaCutanje> getZahtevZaIzjasnjenjeCutanje() {
        if (zalbaCutanje == null) {
        	zalbaCutanje = new ArrayList<ZalbaCutanje>();
        }
        return this.zalbaCutanje;
    }

}
