//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.11 at 11:05:29 AM CET 
//


package com.ftn.xml.jaxb.zalba_cutanje;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}ime_i_prezime"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}adresa"/>
 *           &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}drugi_podaci_za_kontakt"/>
 *           &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}potpis"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imeIPrezime",
    "adresaOrDrugiPodaciZaKontaktOrPotpis"
})
@XmlRootElement(name = "podnosilac_zalbe")
public class PodnosilacZalbe {

    @XmlElement(name = "ime_i_prezime", required = true)
    protected ImeIPrezime imeIPrezime;
    @XmlElements({
        @XmlElement(name = "adresa", type = Adresa.class),
        @XmlElement(name = "drugi_podaci_za_kontakt", type = String.class),
        @XmlElement(name = "potpis", type = Potpis.class)
    })
    protected List<Object> adresaOrDrugiPodaciZaKontaktOrPotpis;

    /**
     * Gets the value of the imeIPrezime property.
     * 
     * @return
     *     possible object is
     *     {@link ImeIPrezime }
     *     
     */
    public ImeIPrezime getImeIPrezime() {
        return imeIPrezime;
    }

    /**
     * Sets the value of the imeIPrezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImeIPrezime }
     *     
     */
    public void setImeIPrezime(ImeIPrezime value) {
        this.imeIPrezime = value;
    }

    /**
     * Gets the value of the adresaOrDrugiPodaciZaKontaktOrPotpis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adresaOrDrugiPodaciZaKontaktOrPotpis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdresaOrDrugiPodaciZaKontaktOrPotpis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Adresa }
     * {@link String }
     * {@link Potpis }
     * 
     * 
     */
    public List<Object> getAdresaOrDrugiPodaciZaKontaktOrPotpis() {
        if (adresaOrDrugiPodaciZaKontaktOrPotpis == null) {
            adresaOrDrugiPodaciZaKontaktOrPotpis = new ArrayList<Object>();
        }
        return this.adresaOrDrugiPodaciZaKontaktOrPotpis;
    }

}
