//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 06:39:47 PM CET 
//


package com.ftn.xml.jaxb.zalba_cutanje;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}ime_i_prezime"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}adresa_podnosioca"/>
 *           &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}drugi_podaci_za_kontakt"/>
 *           &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}potpis"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imeIPrezime",
    "adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis"
})
@XmlRootElement(name = "podnosilac_zalbe")
public class PodnosilacZalbe {

    @XmlElement(name = "ime_i_prezime", required = true)
    protected String imeIPrezime;
    @XmlElementRefs({
        @XmlElementRef(name = "potpis", namespace = "http://ftn.uns.ac.rs/zalba_cutanje", type = Potpis.class, required = false),
        @XmlElementRef(name = "adresa_podnosioca", namespace = "http://ftn.uns.ac.rs/zalba_cutanje", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "drugi_podaci_za_kontakt", namespace = "http://ftn.uns.ac.rs/zalba_cutanje", type = JAXBElement.class, required = false)
    })
    protected List<Object> adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis;

    /**
     * Gets the value of the imeIPrezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeIPrezime() {
        return imeIPrezime;
    }

    /**
     * Sets the value of the imeIPrezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeIPrezime(String value) {
        this.imeIPrezime = value;
    }

    /**
     * Gets the value of the adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Potpis }
     * 
     * 
     */
    public List<Object> getAdresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis() {
        if (adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis == null) {
            adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis = new ArrayList<Object>();
        }
        return this.adresaPodnosiocaOrDrugiPodaciZaKontaktOrPotpis;
    }

}
