//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.11 at 11:05:29 AM CET 
//


package com.ftn.xml.jaxb.zalba_cutanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}naziv_organa"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}razlozi_zalbe"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}datum_zahteva"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/zalba_cutanje}podaci_o_zahtevu_i_informacijama"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivOrgana",
    "razloziZalbe",
    "datumZahteva",
    "podaciOZahtevuIInformacijama"
})
@XmlRootElement(name = "sadrzaj")
public class Sadrzaj {

    @XmlElement(name = "naziv_organa", required = true)
    protected NazivOrgana nazivOrgana;
    @XmlElement(name = "razlozi_zalbe", required = true)
    protected RazloziZalbe razloziZalbe;
    @XmlElement(name = "datum_zahteva", required = true)
    protected DatumZahteva datumZahteva;
    @XmlElement(name = "podaci_o_zahtevu_i_informacijama", required = true)
    protected String podaciOZahtevuIInformacijama;

    /**
     * Gets the value of the nazivOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link NazivOrgana }
     *     
     */
    public NazivOrgana getNazivOrgana() {
        return nazivOrgana;
    }

    /**
     * Sets the value of the nazivOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazivOrgana }
     *     
     */
    public void setNazivOrgana(NazivOrgana value) {
        this.nazivOrgana = value;
    }

    /**
     * Gets the value of the razloziZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link RazloziZalbe }
     *     
     */
    public RazloziZalbe getRazloziZalbe() {
        return razloziZalbe;
    }

    /**
     * Sets the value of the razloziZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link RazloziZalbe }
     *     
     */
    public void setRazloziZalbe(RazloziZalbe value) {
        this.razloziZalbe = value;
    }

    /**
     * Gets the value of the datumZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link DatumZahteva }
     *     
     */
    public DatumZahteva getDatumZahteva() {
        return datumZahteva;
    }

    /**
     * Sets the value of the datumZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatumZahteva }
     *     
     */
    public void setDatumZahteva(DatumZahteva value) {
        this.datumZahteva = value;
    }

    /**
     * Gets the value of the podaciOZahtevuIInformacijama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodaciOZahtevuIInformacijama() {
        return podaciOZahtevuIInformacijama;
    }

    /**
     * Sets the value of the podaciOZahtevuIInformacijama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodaciOZahtevuIInformacijama(String value) {
        this.podaciOZahtevuIInformacijama = value;
    }

}
