//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.04 at 03:32:05 PM CET 
//


package com.ftn.xml.jaxb.resenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}ustanova"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}podnosilac"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}trazeni_dokument"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/resenje}adresa"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ustanova",
    "podnosilac",
    "trazeniDokument",
    "adresa"
})
@XmlRootElement(name = "doneto_resenje")
public class DonetoResenje {

    @XmlElement(required = true)
    protected Ustanova ustanova;
    @XmlElement(required = true)
    protected Podnosilac podnosilac;
    @XmlElement(name = "trazeni_dokument", required = true)
    protected TrazeniDokument trazeniDokument;
    @XmlElement(required = true)
    protected String adresa;

    /**
     * Gets the value of the ustanova property.
     * 
     * @return
     *     possible object is
     *     {@link Ustanova }
     *     
     */
    public Ustanova getUstanova() {
        return ustanova;
    }

    /**
     * Sets the value of the ustanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ustanova }
     *     
     */
    public void setUstanova(Ustanova value) {
        this.ustanova = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link Podnosilac }
     *     
     */
    public Podnosilac getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Podnosilac }
     *     
     */
    public void setPodnosilac(Podnosilac value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the trazeniDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TrazeniDokument }
     *     
     */
    public TrazeniDokument getTrazeniDokument() {
        return trazeniDokument;
    }

    /**
     * Sets the value of the trazeniDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrazeniDokument }
     *     
     */
    public void setTrazeniDokument(TrazeniDokument value) {
        this.trazeniDokument = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresa(String value) {
        this.adresa = value;
    }

}
