//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 06:51:46 PM CET 
//


package com.ftn.xml.jaxb.resenje;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.xml.resenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DatumZahteva_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "datum_zahteva");
    private final static QName _Tacka_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "tacka");
    private final static QName _Taksa_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "taksa");
    private final static QName _Clan_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "clan");
    private final static QName _Adresa_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "adresa");
    private final static QName _Ulica_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "ulica");
    private final static QName _Podnosilac_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "podnosilac");
    private final static QName _Naslov_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "naslov");
    private final static QName _Poverenik_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "poverenik");
    private final static QName _Naziv_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "naziv");
    private final static QName _Sud_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "sud");
    private final static QName _TrazeniDokument_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "trazeni_dokument");
    private final static QName _Datum_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "datum");
    private final static QName _Organ_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "organ");
    private final static QName _Stav_QNAME = new QName("http://ftn.uns.ac.rs/resenje", "stav");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.xml.resenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Uvod }
     * 
     */
    public Uvod createUvod() {
        return new Uvod();
    }

    /**
     * Create an instance of {@link Ustanova }
     * 
     */
    public Ustanova createUstanova() {
        return new Ustanova();
    }

    /**
     * Create an instance of {@link Zakon }
     * 
     */
    public Zakon createZakon() {
        return new Zakon();
    }

    /**
     * Create an instance of {@link SekcijaZakona }
     * 
     */
    public SekcijaZakona createSekcijaZakona() {
        return new SekcijaZakona();
    }

    /**
     * Create an instance of {@link SluzbeniGlasnik }
     * 
     */
    public SluzbeniGlasnik createSluzbeniGlasnik() {
        return new SluzbeniGlasnik();
    }

    /**
     * Create an instance of {@link Resenje }
     * 
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link OsnovniPodaci }
     * 
     */
    public OsnovniPodaci createOsnovniPodaci() {
        return new OsnovniPodaci();
    }

    /**
     * Create an instance of {@link Sadrzaj }
     * 
     */
    public Sadrzaj createSadrzaj() {
        return new Sadrzaj();
    }

    /**
     * Create an instance of {@link Obrazlozenje }
     * 
     */
    public Obrazlozenje createObrazlozenje() {
        return new Obrazlozenje();
    }

    /**
     * Create an instance of {@link ResenjeObrazac }
     * 
     */
    public ResenjeObrazac createResenjeObrazac() {
        return new ResenjeObrazac();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "datum_zahteva")
    public JAXBElement<XMLGregorianCalendar> createDatumZahteva(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumZahteva_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "tacka")
    public JAXBElement<BigInteger> createTacka(BigInteger value) {
        return new JAXBElement<BigInteger>(_Tacka_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "taksa")
    public JAXBElement<Float> createTaksa(Float value) {
        return new JAXBElement<Float>(_Taksa_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "clan")
    public JAXBElement<BigInteger> createClan(BigInteger value) {
        return new JAXBElement<BigInteger>(_Clan_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "adresa")
    public JAXBElement<String> createAdresa(String value) {
        return new JAXBElement<String>(_Adresa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "ulica")
    public JAXBElement<String> createUlica(String value) {
        return new JAXBElement<String>(_Ulica_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "podnosilac")
    public JAXBElement<String> createPodnosilac(String value) {
        return new JAXBElement<String>(_Podnosilac_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "naslov")
    public JAXBElement<String> createNaslov(String value) {
        return new JAXBElement<String>(_Naslov_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "poverenik")
    public JAXBElement<String> createPoverenik(String value) {
        return new JAXBElement<String>(_Poverenik_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "naziv")
    public JAXBElement<String> createNaziv(String value) {
        return new JAXBElement<String>(_Naziv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "sud")
    public JAXBElement<String> createSud(String value) {
        return new JAXBElement<String>(_Sud_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "trazeni_dokument")
    public JAXBElement<String> createTrazeniDokument(String value) {
        return new JAXBElement<String>(_TrazeniDokument_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "datum")
    public JAXBElement<XMLGregorianCalendar> createDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Datum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "organ")
    public JAXBElement<String> createOrgan(String value) {
        return new JAXBElement<String>(_Organ_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/resenje", name = "stav")
    public JAXBElement<BigInteger> createStav(BigInteger value) {
        return new JAXBElement<BigInteger>(_Stav_QNAME, BigInteger.class, null, value);
    }

}
